Controllers/AdminPanelController.cs
using BlogASP.Models;
using BlogASP.Repository;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System.Text;

namespace BlogASP.Controllers
{
    public class AdminPanelController : Controller
    {
        private readonly IUserRepository _userRepository;
        private readonly IArticleRepository _articleRepository;

        public AdminPanelController(IUserRepository userRepository, IArticleRepository articleRepository)
        {
            _userRepository = userRepository;
            _articleRepository = articleRepository;
        }

        public IActionResult Index()
        {
            var viewModel = new AdminPanelViewModel
            {
                Users = _userRepository.GetAll(),
                Articles = _articleRepository.GetAllArticles()
            };
            return View(viewModel);
        }

        public IActionResult Create()
        {
            return View();
        }

        public IActionResult Edit(int id)
        {
            UserModel user = _userRepository.ListById(id);
            return View(user);
        }

        public IActionResult Show()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Create(UserModel user) 
        {
            _userRepository.Create(user);
            return RedirectToAction("Index");
        }

        [HttpPost]
        public IActionResult Edit(UserModel user)
        {
            _userRepository.Edit(user);
            return Redirect("/AdminPanel/Users");
        }


        [HttpPost]
        public IActionResult SetAsPrivileged(int id)
        {
            UserModel user = _userRepository.ListById(id);

            if (user != null && (user.Role == "Public" || user.Role == "Administrator"))
            {
                user.Role = "Privileged";
                _userRepository.Edit(user);

                return Redirect("/AdminPanel/Users");
            }

            return View("Error");
        }

        [HttpPost]
        public IActionResult SetAsPrivilegedPending(int id)
        {
            UserModel user = _userRepository.ListById(id);

            if (user != null && (user.Role == "Public" || user.Role == "Administrator"))
            {
                user.Role = "Privileged";
                _userRepository.Edit(user);

                return Redirect("/AdminPanel/PendingUsers");
            }

            return View("Error");
        }

        [HttpPost]
        public IActionResult SetAsPublicUser(int id)
        {
            UserModel user = _userRepository.ListById(id);

            if (user != null && (user.Role == "Privileged" || user.Role == "Administrator"))
            {
                user.Role = "Public";
                _userRepository.Edit(user);

                return Redirect("/AdminPanel/Users");
            }

            return View("Error");
        }

        [HttpPost]
        public IActionResult SetAsAdministrator(int id)
        {
            UserModel user = _userRepository.ListById(id);

            if (user != null && user.Role == "Privileged")
            {
                user.Role = "Administrator";
                _userRepository.Edit(user);

                return Redirect("/AdminPanel/Users");
            }

            return View("Error");
        }

        [HttpPost]
        public IActionResult DisableUser(int id)
        {
            UserModel user = _userRepository.ListById(id);

            if (user != null)
            {
                user.Role = "Disabled";
                user.DeletedAt = DateTime.Now;
                _userRepository.Edit(user);
            }

            return Redirect("/AdminPanel/Users");
        }

        [HttpPost]
        public IActionResult DisableUserPending(int id)
        {
            UserModel user = _userRepository.ListById(id);

            if (user != null)
            {
                user.Role = "Disabled";
                user.DeletedAt = DateTime.Now;
                _userRepository.Edit(user);
            }

            return Redirect("/AdminPanel/PendingUsers");
        }

        [HttpPost]
        public IActionResult DisableArticle(int id)
        {
            ArticleModel article = _articleRepository.GetArticleById(id);

            if (article != null)
            {
                article.isDisabled = true;
                article.DeletedAt = DateTime.Now;
                _articleRepository.Edit(article);
            }

            return Redirect("/AdminPanel/Articles");
        }

        [HttpPost]
        public IActionResult EnableArticle(int id)
        {
            ArticleModel article = _articleRepository.GetArticleById(id);

            if (article != null)
            {
                article.isDisabled = false;
                article.UpdatedAt = DateTime.Now;
                _articleRepository.Edit(article);
            }
            return Redirect("/AdminPanel/Articles");
        }

        [HttpPost]
        public IActionResult EnableUser(int id)
        {
            UserModel user = _userRepository.ListById(id);

            if (user != null)
            {
                user.Role = "Public";
                _userRepository.Edit(user);
            }

            return Redirect("/AdminPanel/Users");
        }

        public IActionResult EditArticle(int id)
        {
            ArticleModel article = _articleRepository.GetArticleById(id);

            if (article == null)
            {
                return View("Error");
            }

            return View("EditArticle", article);
        }

        [HttpPost]
        public IActionResult UpdateArticle(int id, ArticleModel updatedArticle)
        {
            if (ModelState.IsValid)
            {
                ArticleModel existingArticle = _articleRepository.GetArticleById(id);

                if (existingArticle == null)
                {
                    return NotFound();
                }

                existingArticle.Title = updatedArticle.Title;
                existingArticle.Category = updatedArticle.Category;
                existingArticle.Description = updatedArticle.Description;
                existingArticle.isPrivate = updatedArticle.isPrivate;
                existingArticle.UpdatedAt = DateTime.Now;

                updatedArticle.Stars = existingArticle.Stars;

                _articleRepository.UpdateArticle(existingArticle);

                return RedirectToAction("Articles"); // Redirect to the admin panel articles page
            }

            return View("EditArticle", updatedArticle);
        }

        [HttpPost]
        public IActionResult CreateAdmin(UserModel user)
        {
            if (ModelState.IsValid)
            {
                var existingUser = _userRepository.GetUserByUsername(user.Username);
                if (existingUser != null)
                {
                    ModelState.AddModelError(string.Empty, "Username already exists");
                    return View("Create");
                }
                string hashedPassword = PasswordHasher.HashPassword(user.Password);
                user.Password = hashedPassword;

                _userRepository.Create(user);

                return RedirectToAction("Index");
            }
            return View("Create");
        }

        public IActionResult PendingUsers()
        {
            var viewModel = new AdminPanelViewModel
            {
                Users = _userRepository.GetAll()
            };
            return View(viewModel);
        }

        public IActionResult Users()
        {
            var viewModel = new AdminPanelViewModel
            {
                Users = _userRepository.GetAll()
            };
            return View(viewModel);
        }

        public IActionResult Articles()
        {
            var viewModel = new AdminPanelViewModel
            {
                Articles = _articleRepository.GetAllArticles()
            };
            return View(viewModel);
        }

        [HttpGet]
        [HttpPost]
        public IActionResult ExportPendingUsersToCSV()
        {
            var pendingUsers = _userRepository.GetAll().Where(u => u.Role == "Public");

            var csvData = new StringBuilder();
            csvData.AppendLine("UserId,Name,Username,Email");

            foreach (var user in pendingUsers)
            {
                csvData.AppendLine($"{user.UserId},{user.Name},{user.Username},{user.Email}");
            }

            var csvFileName = "exported_pending_users.csv";
            var csvBytes = Encoding.UTF8.GetBytes(csvData.ToString());
            return File(csvBytes, "text/csv", csvFileName);
        }

        [HttpGet]
        [HttpPost]
        public IActionResult ExportUsersToCSV()
        {
            var users = _userRepository.GetAll();

            var csvData = new StringBuilder();
            csvData.AppendLine("UserId,Name,Username,Email,Role,CreatedAt,UpdatedAt,DeletedAt");

            foreach (var user in users)
            {
                csvData.AppendLine($"{user.UserId},{user.Name},{user.Username},{user.Email},{user.Role},{user.CreatedAt},{user.UpdatedAt},{user.DeletedAt}");
            }

            var csvFileName = "exported_users.csv";
            var csvBytes = Encoding.UTF8.GetBytes(csvData.ToString());
            return File(csvBytes, "text/csv", csvFileName);
        }

        [HttpGet]
        [HttpPost]
        public IActionResult ExportArticlesToCSV()
        {
            var articles = _articleRepository.GetAllArticles();

            var csvData = new StringBuilder();
            csvData.AppendLine("ArticleId,Title,Category,Stars,isPrivate,isDisabled,DeletedAt");

            foreach (var article in articles)
            {
                csvData.AppendLine($"{article.ArticleId},{article.Title},{article.Category},{article.Stars},{article.isPrivate},{article.isDisabled},{article.DeletedAt}");
            }

Controllers/LoginController.cs
using BlogASP.Repository;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Http;
using BlogASP.Models;
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Authentication;
using System.Security.Claims;

namespace BlogASP.Controllers
{
    public class LoginController : Controller
    {
        private readonly IUserRepository _userRepository;

        public LoginController(IUserRepository userRepository)
        {
            _userRepository = userRepository;
        }
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Logout()
        {
            HttpContext.SignOutAsync(CookieAuthenticationDefaults.AuthenticationScheme);
            return RedirectToAction("Index", "Home");
        }

        [HttpPost]
        public IActionResult Login(UserModel loginModel)
        {
            var user = _userRepository.GetAll().FirstOrDefault(u => u.Username == loginModel.Username);

            if (user != null && PasswordHasher.VerifyPassword(user.Password, loginModel.Password))
            {
                if (user.Role == "Disabled")
                {
                    ModelState.Remove("Role");
                    TempData["CustomError"] = "Your account is disabled.";
                    return View("Index");
                }

                var claims = new List<Claim>
                {
                    new Claim(ClaimTypes.Name, user.Username),
                    new Claim(ClaimTypes.Role, user.Role)
                };

                var identity = new ClaimsIdentity(claims, CookieAuthenticationDefaults.AuthenticationScheme);
                var principal = new ClaimsPrincipal(identity);

                HttpContext.SignInAsync(CookieAuthenticationDefaults.AuthenticationScheme, principal);

                return RedirectToAction("Index", "Home");
            }
            else
            {
                TempData["CustomError"] = "Username or Password incorrect. Try again!";
                return Redirect("/Login");
            }
        }
    }
}

Controllers/SignUpController.cs
using BlogASP.Models;
using BlogASP.Repository;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Mvc;
using System.Security.Claims;

namespace BlogASP.Controllers
{
    public class SignUpController : Controller
    {
        private readonly IUserRepository _userRepository;
        private readonly IHttpContextAccessor _httpContextAccessor;

        public SignUpController(IUserRepository userRepository, IHttpContextAccessor httpContextAccessor)
        {
            _userRepository = userRepository;
            _httpContextAccessor = httpContextAccessor;
        }

        public IActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Create(UserModel user)
        {
            List<string> errors = new List<string>();

            var existingUser = _userRepository.GetUserByUsername(user.Username);
            if (existingUser != null)
            {
                errors.Add("Username already exists.Please try another!");
            }

            existingUser = _userRepository.GetUserByEmail(user.Email);
            if (existingUser != null)
            {
                errors.Add("Email already exists.Please try another!");
            }

            if (errors.Count > 0)
            {
                ViewData["CustomErrors"] = errors; 
                return View("Index", user);
            }

            var passwordHash = PasswordHasher.HashPassword(user.Password);
            user.Password = passwordHash;

            var claims = new List<Claim>
            {
                new Claim(ClaimTypes.Name, user.Username),
            };

            var claimsIdentity = new ClaimsIdentity(claims, CookieAuthenticationDefaults.AuthenticationScheme);
            var authProperties = new AuthenticationProperties();

            await HttpContext.SignInAsync(CookieAuthenticationDefaults.AuthenticationScheme, new ClaimsPrincipal(claimsIdentity), authProperties);

            _userRepository.Create(user);

            return RedirectToAction("Index", "Home");
        }

    }

}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - BlogASP</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/BlogASP.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.1/css/all.min.css" integrity="sha512-qIY/AJSo5u75g1IjPBOeWTiwrPtk2TGNc/TkqFaeXM8dZIxDHvMMEBs5YdNPzR+YMqEgthJbG0bMLeX66Of7cA==" crossorigin="anonymous" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Article" asp-action="Index">Articles</a>
                            </li>
                        @if (User.Identity.IsAuthenticated && User.IsInRole("Administrator"))
                        {
                            <li class="nav-item dropdown">
                                <a class="nav-link dropdown-toggle text-dark" href="#" id="adminDropdown" role="button" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                    Admin Menu
                                </a>
                                <div class="dropdown-menu" aria-labelledby="adminDropdown">
                                    <a class="dropdown-item" asp-area="" asp-controller="AdminPanel" asp-action="PendingUsers">Pending Users</a>
                                    <a class="dropdown-item" asp-area="" asp-controller="AdminPanel" asp-action="Users">Users</a>
                                    <a class="dropdown-item" asp-area="" asp-controller="AdminPanel" asp-action="Articles">Articles</a>
                                    <a class="dropdown-item" asp-controller="AdminPanel" asp-action="Create" >
                                        New User
                                        <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-person-plus" viewBox="0 0 16 16">
                                            <path d="M6 8a3 3 0 1 0 0-6 3 3 0 0 0 0 6zm2-3a2 2 0 1 1-4 0 2 2 0 0 1 4 0zm4 8c0 1-1 1-1 1H1s-1 0-1-1 1-4 6-4 6 3 6 4zm-1-.004c-.001-.246-.154-.986-.832-1.664C9.516 10.68 8.289 10 6 10c-2.29 0-3.516.68-4.168 1.332-.678.678-.83 1.418-.832 1.664h10z" />
                                            <path fill-rule="evenodd" d="M13.5 5a.5.5 0 0 1 .5.5V7h1.5a.5.5 0 0 1 0 1H14v1.5a.5.5 0 0 1-1 0V8h-1.5a.5.5 0 0 1 0-1H13V5.5a.5.5 0 0 1 .5-.5z" />
                                        </svg>
                                    </a>
                                    <a class="dropdown-item btn-export1" asp-controller="AdminPanel" asp-action="ExportAllToCSV">
                                        Export All Data
                                        <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-file-earmark-arrow-down" viewBox="0 0 16 16">
                                            <path d="M8.5 6.5a.5.5 0 0 0-1 0v3.793L6.354 9.146a.5.5 0 1 0-.708.708l2 2a.5.5 0 0 0 .708 0l2-2a.5.5 0 0 0-.708-.708L8.5 10.293V6.5z" />
                                            <path d="M14 14V4.5L9.5 0H4a2 2 0 0 0-2 2v12a2 2 0 0 0 2 2h8a2 2 0 0 0 2-2zM9.5 3A1.5 1.5 0 0 0 11 4.5h2V14a1 1 0 0 1-1 1H4a1 1 0 0 1-1-1V2a1 1 0 0 1 1-1h5.5v2z" />
                                        </svg>
                                    </a>
                                </div>
                            </li>
                        }
                    </ul>
                    <ul class="navbar-nav">
                        @if (!User.Identity.IsAuthenticated)
                        {
                            <li class="nav-item">
                                <a class="nav-link btn btn-light text-dark" href="@Url.Action("Index", "Login")">Login</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link btn btn-light text-dark" href="@Url.Action("Index", "SignUp")">SignUp</a>
                            </li>
                        }
                        @if (User.Identity.IsAuthenticated)
                        {
                            <li class="nav-item d-flex align-items-center">
                                <span class="nav-link text-dark">
                                    <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-person-workspace" viewBox="0 0 16 16">
                                        <path d="M4 16s-1 0-1-1 1-4 5-4 5 3 5 4-1 1-1 1H4Zm4-5.95a2.5 2.5 0 1 0 0-5 2.5 2.5 0 0 0 0 5Z" />
                                        <path d="M2 1a2 2 0 0 0-2 2v9.5A1.5 1.5 0 0 0 1.5 14h.653a5.373 5.373 0 0 1 1.066-2H1V3a1 1 0 0 1 1-1h12a1 1 0 0 1 1 1v9h-2.219c.554.654.89 1.373 1.066 2h.653a1.5 1.5 0 0 0 1.5-1.5V3a2 2 0 0 0-2-2H2Z" />
                                    </svg>
                                    @User.Identity.Name</span>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link btn btn-light text-dark" asp-action="Logout" asp-controller="Login" method="post">Logout</a>
                            </li>
                        }
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>
    <br>
    <footer class="border-top footer text-muted text-center">
        <div class="container">
            &copy; 2023 - All Rights Reserved
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @await RenderSectionAsync("Scripts", required: false)
    @Html.ValidationSummary()
</body>
</html>
<style>
    footer{
        z-index: 100;
        background-color: #FFF;
    }

    .btn-light {
        background-color: #f8f9fa;
        color: #343a40;
        margin-right: 10px;
    }

        .btn-light:hover {
            background-color: #e2e6ea;
        }

    .nav-link.btn {
        display: flex;
        align-items: center;
    }


    .btn-export1:hover {
        color: #00BFFF;
    }

</style>